server:
 port: 4041
spring:
 application:
  name: ReportAPI
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql:///ReportAPI
  username: root
  password: root
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.mysql.dialect.MYSQL8Dialect
  